spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.103.167:3307/jpashop?characterEncoding=UTF-8
    username: root
    password: root
#    url: jdbc:h2:tcp://localhost/~/jpashop;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug #jpa? sql? ??? ??? ????.
    org.hibernate.type: trace # ?? ????? ?? ????? ??
